import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import Header from "@/components/Header";
import { Roboto_Slab } from "next/font/google"

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-slab",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EMB PRODUCTIONS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoSlab.variable + " antialiased bg-[#0b0813]"}>
        <div className="relative border h-[100vh]">
          <div className="absolute bottom-5 right-5 rotate-180">
            <svg width="20" height="20" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="0.5" x2="-4.15258e-08" y2="0.499999" stroke="white"></line>
              <line x1="0.5" y1="10" x2="0.500001" y2="-6.55671e-08" stroke="white"></line>
            </svg>
          </div>
          <div className="absolute bottom-5 left-5 rotate-90">
            <svg width="20" height="20" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="0.5" x2="-4.15258e-08" y2="0.499999" stroke="white"></line>
              <line x1="0.5" y1="10" x2="0.500001" y2="-6.55671e-08" stroke="white"></line>
            </svg>
          </div>
        </div>
        <Header/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
