
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { Roboto_Slab } from "next/font/google"
import MouseStats from "@/components/MouseStats";
import Noise from "@/components/Noise";
import SystemStats from "@/components/SystemStats";
import BgVideo from "@/components/BgVideo";
import ClientLayout from "@/components/ClientLayout";
// import EmbLogo from "@/components/EmbLogo";

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-slab",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EMB PRODUCTIONS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} ${geistMono.variable} antialiased bg-[#0b0813]`}>
        <div className="hidden lg:block"><MouseStats /></div>
        {/* ONLY DESKTOP */}
        <div className="fixed w-full hidden lg:block">
          <div className="absolute h-[100vh] flex items-center left-5">
            <svg width="10" height="20" viewBox="0 0 10 20" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="10.5" x2="-4.15258e-08" y2="10.5" stroke="white"></line>
              <line x1="0.5" y1="20" x2="0.499999" y2="2.18557e-08" stroke="white"></line>
            </svg>
          </div>
          <div className="absolute h-[100vh] flex items-center right-5 rotate-180">
            <svg width="10" height="20" viewBox="0 0 10 20" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="10.5" x2="-4.15258e-08" y2="10.5" stroke="white"></line>
              <line x1="0.5" y1="20" x2="0.499999" y2="2.18557e-08" stroke="white"></line>
            </svg>
          </div>
          <div className="absolute top-5 right-5 rotate-90">
            <svg width="10" height="20" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="0.5" x2="-4.15258e-08" y2="0.499999" stroke="white"></line>
              <line x1="0.5" y1="10" x2="0.500001" y2="-6.55671e-08" stroke="white"></line>
            </svg>
          </div>
          <div className="absolute top-5 left-5">
            <svg width="10" height="20" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="0.5" x2="-4.15258e-08" y2="0.499999" stroke="white"></line>
              <line x1="0.5" y1="10" x2="0.500001" y2="-6.55671e-08" stroke="white"></line>
            </svg>
          </div>
        </div>
        {/* MOBILE AND DESKTOP ALWAYS */}
        <div className="fixed w-full h-[100vh]">
          <div className="absolute bottom-5 right-5 rotate-180">
            <svg width="10" height="20" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="0.5" x2="-4.15258e-08" y2="0.499999" stroke="white"></line>
              <line x1="0.5" y1="10" x2="0.500001" y2="-6.55671e-08" stroke="white"></line>
            </svg>
          </div>
          <div className="absolute bottom-5 left-5 -rotate-90">
            <svg width="10" height="20" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
              <line x1="10" y1="0.5" x2="-4.15258e-08" y2="0.499999" stroke="white"></line>
              <line x1="0.5" y1="10" x2="0.500001" y2="-6.55671e-08" stroke="white"></line>
            </svg>
          </div>
        </div>

        {/* Header + BgVideo + contenido, controlados desde un componente cliente */}
        <ClientLayout>
          {children}
        </ClientLayout>

        {/* Logo EMB superior central */}
        {/* <div className="hidden lg:block absolute top-8 left-1/2 -translate-x-1/2 z-10 pointer-events-none select-none">
          <EmbLogo className="w-16 h-auto drop-shadow-[0_0_20px_rgba(147,51,234,0.7)]" />
        </div> */}

        {/* Texto técnico de fondo superior central */}
        <div className="hidden lg:block absolute top-32 left-1/2 -translate-x-1/2 z-10 pointer-events-none select-none">
          <div className="font-mono text-[11px] text-white/25 tracking-wider leading-relaxed text-center">
            <div className="-mb-2">VIDEO_ID / AAN_GM1GN2GFEA2GA / POKE_XERK_VVYC</div>
            <div className="-mb-2">VIEWPORT / FRAMES 1920X1080*1.20 - 0 DROPPED OF 80GEN</div>
            <div className="-mb-2">CLIPPING / PIXEL_COORDINATES / 1920:1080@60 / 0BNG2X12L9M825</div>
            <div className="-mb-2">VOLUME / NORMALIZED 100% / 100% [CONTENT_LOUDNESS -25.8DB]</div>
            <div>CODECS MV1A 2.8:665:15:0 / OPUS [20]</div>
          </div>
        </div>
        <div className="hidden lg:block absolute z-1 top-80 left-30">
          <SystemStats loaded={4} total={28} />
        </div>
        <div className="hidden lg:block absolute z-1 bottom-10 right-40">
          <SystemStats loaded={4} total={28} />
        </div>
        <div className="hidden lg:block">
          <img
            src="/picto3.webp"
            alt="Fondo"
            className="object-cover absolute top-20 left-68 w-5 opacity-30"
          />
          <img
            src="/picto3.webp"
            alt="Fondo"
            className="object-cover absolute top-100 left-100 w-5 opacity-30"
          />
          <img
            src="/picto1.webp"
            alt="Fondo"
            className="object-cover absolute bottom-40 left-40 w-5 opacity-30"
          />
          <img
            src="/picto1.webp"
            alt="Fondo"
            className="object-cover absolute top-30 right-40 w-5 opacity-30"
          />
          <img
            src="/picto1.webp"
            alt="Fondo"
            className="object-cover absolute bottom-30 right-100 w-5 opacity-30"
          />
          <img
            src="/picto1.webp"
            alt="Fondo"
            className="object-cover absolute bottom-50 right-30 w-5 opacity-30"
          />
          <img
            src="/picto2.webp"
            alt="Fondo"
            className="object-cover absolute top-16 left-90 w-4 opacity-30"
          />
          <img
            src="/picto2.webp"
            alt="Fondo"
            className="object-cover absolute top-100 left-90 w-4 opacity-30"
          />
        </div>
        <div className="fixed inset-0 -z-10 w-full h-full bg-white brightness-100">
          <img
            src="/bg.jpg"
            alt="Fondo"
            className="w-full h-full object-cover object-center brightness-150 mix-blend-multiply"
          />
        </div>
        <div className="fixed inset-0 -z-10 w-full h-full">
          <div className="absolute top-0 w-full overflow-hidden h-full mask-[url(/cubo.png)] mask-size-[.2%]">
            <Noise
              patternSize={50}
              patternScaleX={1}
              patternScaleY={1}
              patternRefreshInterval={8}
              patternAlpha={16}
            />
          </div>

        </div>
      </body>
    </html>
  );
}
