import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto_Flex } from "next/font/google";
import ClickSpark from "@/components/ClickSpark";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  axes: ["wght", "opsz"], // importante para variaciones
  variable: "--font-roboto-flex",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EMB PRODUCTIONS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoFlex.variable + " antialiased bg-[#0b0813]"}>
        <ClickSpark
          sparkColor='#fff'
          sparkSize={10}
          sparkRadius={15}
          sparkCount={8}
          duration={400}
        >
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
